{{- if and .Values.accounts (.Values.accounts.grouped) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}-accounts
data:
  accounts.yaml: |
    accounts:
{{- $providers := list "aliyun" "tencent" "huawei" "aws" }}
{{- range $provider := $providers }}
{{- $accList := index $.Values.accounts.grouped $provider }}
{{- if gt (len $accList) 0 }}
      {{ $provider }}:
{{- range $i, $a := $accList }}
        - account_id: ${ {{ $provider | upper }}_ACC_{{ $i }}_ID}
          access_key_id: ${ {{ $provider | upper }}_ACC_{{ $i }}_AK}
          access_key_secret: ${ {{ $provider | upper }}_ACC_{{ $i }}_SK}
{{- if $a.regions }}
          regions: {{ toYaml $a.regions | nindent 12 -}}
{{- end }}
{{- if $a.resources }}
          resources: {{ toYaml $a.resources | nindent 12 -}}
{{- end }}
{{- end }}
{{- else }}
      {{ $provider }}: []
{{- end }}
{{- end }}
{{- end }}
