{
 "title": "L2-共享带宽 (BWP)",
 "tags": [
  "network",
  "bwp",
  "mce"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "cloud_provider",
    "label": "云厂商",
    "query": {
     "query": "label_values(bwp_in_bps,cloud_provider)"
    }
   },
   {
    "name": "account_id",
    "label": "账号",
    "query": "label_values(bwp_in_bps{cloud_provider=~\"$cloud_provider\"}, account_id)"
   },
   {
    "name": "region",
    "label": "区域",
    "query": "label_values(bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\"}, region)"
   },
   {
    "name": "resource_id",
    "label": "共享带宽ID",
    "query": "label_values(bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\"}, resource_id)"
   },
   {
    "name": "code_name",
    "label": "CodeName",
    "query": {
     "query": "label_values(bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\"},code_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$region 区域总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "📊 区域总览",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (account_id) (bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "账号总数"
    },
    {
     "expr": "count(count by (resource_id) (bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "共享带宽总数"
    }
   ]
  },
  {
   "title": "入方向关键指标",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bwp_in_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "平均流入使用率"
    },
    {
     "expr": "sum(bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}) / 1000000",
     "legendFormat": "总流入带宽"
    },
    {
     "expr": "sum(bwp_in_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "总流入包速率"
    },
    {
     "expr": "sum(bwp_in_drop_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "入方向丢包"
    }
   ]
  },
  {
   "title": "出方向关键指标",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bwp_out_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "平均流出使用率"
    },
    {
     "expr": "sum(bwp_out_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}) / 1000000",
     "legendFormat": "总流出带宽"
    },
    {
     "expr": "sum(bwp_out_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "总流出包速率"
    },
    {
     "expr": "sum(bwp_out_drop_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "出方向丢包"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bwp_in_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "入方向使用率"
    },
    {
     "expr": "bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"} / 1000000",
     "legendFormat": "入方向流量"
    },
    {
     "expr": "bwp_out_utilization_pct{ account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "出方向使用率"
    },
    {
     "expr": "bwp_out_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"} / 1000000",
     "legendFormat": "出方向流量"
    },
    {
     "expr": "bwp_in_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "入方向丢包"
    },
    {
     "expr": "bwp_out_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "出方向丢包"
    },
    {
     "expr": "max by(cloud_provider,account_id,region,resource_id,code_name) (max_over_time(bwp_in_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "入方向最大使用率"
    },
    {
     "expr": "max by(cloud_provider,account_id,region,resource_id,code_name) (max_over_time(bwp_out_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "出方向最大使用率"
    }
   ]
  },
  {
   "title": "入方向带宽趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "bwp_in_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"} / 1000000",
     "legendFormat": "{{resource_id}} - 流入带宽(Mbps)"
    }
   ]
  },
  {
   "title": "入方向包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "bwp_in_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 流入包速率"
    }
   ]
  },
  {
   "title": "入方向丢包",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "bwp_in_drop_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 入方向丢包"
    }
   ]
  },
  {
   "title": "出方向带宽趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "bwp_out_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"} / 1000000",
     "legendFormat": "{{resource_id}} - 流出带宽(Mbps)"
    }
   ]
  },
  {
   "title": "出方向包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "bwp_out_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 流出包速率"
    }
   ]
  },
  {
   "title": "出方向丢包",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "bwp_out_drop_pps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 出方向丢包"
    }
   ]
  }
 ]
}