{
 "title": "L2-负载均衡（LB）",
 "tags": [
  "network",
  "lb",
  "mce"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "cloud_provider",
    "label": "云厂商",
    "query": {
     "query": "label_values(lb_active_connection{cloud_provider=~\"$cloud_provider\"},cloud_provider)"
    }
   },
   {
    "name": "account_id",
    "label": "账号",
    "query": {
     "query": "label_values(lb_active_connection{cloud_provider=~\"$account_id|$cloud_provider\", account_id=~\"$account_id\"},account_id)"
    }
   },
   {
    "name": "region",
    "label": "地域",
    "query": {
     "query": "label_values(lb_active_connection{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\"},region)"
    }
   },
   {
    "name": "resource_id",
    "label": "资源ID",
    "query": {
     "query": "label_values(lb_active_connection{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\"},resource_id)"
    }
   },
   {
    "name": "code_name",
    "label": "业务名",
    "query": {
     "query": "label_values(lb_active_connection{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"},code_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "七层 QPS 总览",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lb_qps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "总 QPS"
    }
   ]
  },
  {
   "title": "七层 RT 总览",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(lb_rt{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "平均 RT"
    }
   ]
  },
  {
   "title": "📊 全局总览",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (account_id) (lb_traffic_rx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "账号总数"
    },
    {
     "expr": "count(count by (resource_id) (lb_traffic_rx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}))",
     "legendFormat": "负载均衡总数"
    }
   ]
  },
  {
   "title": "入方向关键指标",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(lb_traffic_rx_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "平均流入使用率"
    },
    {
     "expr": "sum(lb_traffic_rx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}) / 1000000",
     "legendFormat": "总流入带宽"
    },
    {
     "expr": "sum(lb_packet_rx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "总流入包速率"
    },
    {
     "expr": "sum(lb_drop_packet_rx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "入方向丢包"
    }
   ]
  },
  {
   "title": "出方向关键指标",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(lb_traffic_tx_utilization_pct{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "平均流出使用率"
    },
    {
     "expr": "sum(lb_traffic_tx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}) / 1000000",
     "legendFormat": "总流出带宽"
    },
    {
     "expr": "sum(lb_packet_tx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "总流出包速率"
    },
    {
     "expr": "sum(lb_drop_packet_tx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"})",
     "legendFormat": "出方向丢包"
    }
   ]
  },
  {
   "title": "入方向带宽",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "lb_traffic_rx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 入带宽"
    }
   ]
  },
  {
   "title": "出方向带宽",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "lb_traffic_tx_bps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 出带宽"
    }
   ]
  },
  {
   "title": "入方向包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "lb_packet_rx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 入包"
    }
   ]
  },
  {
   "title": "出方向包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "lb_packet_tx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 出包"
    }
   ]
  },
  {
   "title": "七层 5xx 状态码",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "lb_status_code_5xx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 5xx"
    }
   ]
  },
  {
   "title": "七层 QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "lb_qps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - QPS"
    }
   ]
  },
  {
   "title": "七层 RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "lb_rt{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - RT"
    }
   ]
  },
  {
   "title": "后端异常实例数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lb_unhealthy_server_count{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 异常服务器"
    }
   ]
  },
  {
   "title": "实例 QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "lb_instance_qps{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 实例QPS"
    }
   ]
  },
  {
   "title": "实例 RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "lb_instance_rt{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 实例RT"
    }
   ]
  },
  {
   "title": "实例入包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "lb_instance_packet_rx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 入包"
    }
   ]
  },
  {
   "title": "实例出包速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "lb_instance_packet_tx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 出包"
    }
   ]
  },
  {
   "title": "状态码分布",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "lb_status_code_2xx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 2xx"
    },
    {
     "expr": "lb_status_code_3xx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 3xx"
    },
    {
     "expr": "lb_status_code_4xx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 4xx"
    },
    {
     "expr": "lb_status_code_5xx{cloud_provider=~\"$cloud_provider\", account_id=~\"$account_id\", region=~\"$region\", resource_id=~\"$resource_id\", code_name=~\"$code_name\"}",
     "legendFormat": "{{resource_id}} - 5xx"
    }
   ]
  }
 ]
}